== `rpicam-apps`

[NOTE]
====
Raspberry Pi OS _Bookworm_ renamed the camera capture applications from ``libcamera-\*`` to ``rpicam-*``. Symbolic links allow users to use the old names for now. **Adopt the new application names as soon as possible.** Raspberry Pi OS versions prior to _Bookworm_ still use the ``libcamera-*`` name.
====

Raspberry Pi supplies a small set of example `rpicam-apps`. These CLI applications, built on top of `libcamera`, capture images and video from a camera. These applications include:

* `rpicam-hello`: A "hello world"-equivalent for cameras, which starts a camera preview stream and displays it on the screen.
* `rpicam-jpeg`: Runs a preview window, then captures high-resolution still images.
* `rpicam-still`: Emulates many of the features of the original `raspistill` application.
* `rpicam-vid`: Captures video.
* `rpicam-raw`: Captures raw (unprocessed Bayer) frames directly from the sensor.
* `rpicam-detect`: Not built by default, but users can build it if they have TensorFlow Lite installed on their Raspberry Pi. Captures JPEG images when certain objects are detected.
* `rpicam-source`: Provides a source camera application with an integrated HTTP server. This allows clients to control video capture via REST-like endpoints (e.g. `/start`, `/stop`, `/video_name`, and `/status`).
* `rpicam-sink`: A sink application designed to receive and process video frames streamed from `rpicam-source`.

Recent versions of Raspberry Pi OS include the basic set of `rpicam-apps`, so you can record images and videos using a camera even on a fresh Raspberry Pi OS installation.

Users can create their own `rpicam`-based applications with custom functionality to suit their own requirements. The [rpicam-apps source code](https://github.com/raspberrypi/rpicam-apps) is freely available under a BSD-2-Clause licence.

=== `libcamera`

`libcamera` is an open-source software library aimed at supporting camera systems directly from the Linux operating system on Arm processors. Proprietary code running on the Broadcom GPU is minimised. For more information about `libcamera` see the [libcamera website](https://libcamera.org).

`libcamera` provides a {cpp} API that configures the camera, then allows applications to request image frames. These image buffers reside in system memory and can be passed directly to still image encoders (such as JPEG) or to video encoders (such as H.264). `libcamera` doesn't encode or display images itself: that functionality is provided by applications such as `rpicam-apps`.

You can find the source code in the [official libcamera repository](https://git.linuxtv.org/libcamera.git). The Raspberry Pi OS distribution uses a [fork of libcamera](https://github.com/raspberrypi/libcamera.git) to control updates.

Underneath the `libcamera` core, we provide a custom pipeline handler. `libcamera` uses this layer to drive the sensor and image signal processor (ISP) on the Raspberry Pi. `libcamera` contains a collection of image-processing algorithms (IPAs) including auto exposure/gain control (AEC/AGC), auto white balance (AWB), and auto lens-shading correction (ALSC).

Raspberry Pi's implementation of `libcamera` supports the following cameras:

* Official cameras:
** OV5647 (V1)
** IMX219 (V2)
** IMX708 (V3)
** IMX477 (HQ)
** IMX500 (AI)
** IMX296 (GS)
* Third-party sensors:
** IMX290
** IMX327
** IMX378
** IMX519
** OV9281

To extend support to a new sensor, consider contributing to [libcamera](https://git.linuxtv.org/libcamera.git).
